"use client";
import { useEffect, useRef, useState } from "react";

// "Prep me" — one-tap pre-call brief synthesized from everything the app knows
// about this account. Renders inline; copyable for pasting into notes.
type Brief = { headline: string; situation: string[]; money: string[]; people: string[]; opener: string; questions: string[]; proof: string };

export default function PrepBrief({ accountId }: { accountId: string }) {
  const [state, setState] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [brief, setBrief] = useState<Brief | null>(null);
  const [err, setErr] = useState("");
  const [elapsed, setElapsed] = useState(0);
  const [copied, setCopied] = useState(false);
  const timer = useRef<ReturnType<typeof setInterval> | undefined>(undefined);
  useEffect(() => () => clearInterval(timer.current), []);

  async function generate() {
    setState("loading"); setErr(""); setElapsed(0); setCopied(false);
    const t0 = Date.now();
    timer.current = setInterval(() => setElapsed(Math.round((Date.now() - t0) / 1000)), 1000);
    try {
      const r = await fetch("/api/prep-brief", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accountId }) });
      const j = await r.json().catch(() => null);
      if (!r.ok || !j?.brief) { setErr(j?.error || "Couldn't build the brief — try again."); setState("error"); return; }
      setBrief(j.brief); setState("done");
    } catch { setErr("Network error."); setState("error"); }
    finally { clearInterval(timer.current); }
  }

  function copyText() {
    if (!brief) return;
    const t = [
      `PRE-CALL BRIEF — ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`,
      "", brief.headline, "",
      "SITUATION", ...brief.situation.map((s) => `• ${s}`), "",
      "THE MONEY STORY", ...brief.money.map((s) => `• ${s}`), "",
      "PEOPLE", ...brief.people.map((s) => `• ${s}`), "",
      "OPENER", brief.opener, "",
      "DISCOVERY QUESTIONS", ...brief.questions.map((q, i) => `${i + 1}. ${q}`),
      ...(brief.proof ? ["", "PROOF POINT", brief.proof] : []),
      "", "Generated by AccountFluency from filings, FERC/EIA data, and your CRM — verify before relying on it.",
    ].join("\n");
    navigator.clipboard.writeText(t).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
  }

  const Sec = ({ t, items }: { t: string; items: string[] }) => items.length === 0 ? null : (
    <div style={{ marginBottom: 10 }}>
      <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: ".6px", color: "#9A6700", marginBottom: 3 }}>{t}</div>
      {items.map((s, i) => <div key={i} style={{ fontSize: 13.5, lineHeight: 1.5, padding: "1px 0 1px 12px", textIndent: -12 }}>• {s}</div>)}
    </div>
  );

  if (state === "idle" || state === "loading" || state === "error") {
    return (
      <div style={{ margin: "10px 0 2px" }}>
        <button onClick={generate} disabled={state === "loading"}
          style={{ width: "100%", background: "linear-gradient(135deg, #2B2620, #4A4238)", color: "#F5EFE3", border: "none", borderRadius: 12, padding: "13px 16px", fontSize: 14.5, fontWeight: 800, cursor: state === "loading" ? "default" : "pointer", opacity: state === "loading" ? 0.85 : 1 }}>
          {state === "loading" ? `🧠 Building your brief… ${elapsed}s (~20s)` : "🧠 Prep me for this meeting"}
        </button>
        {state === "error" && <p style={{ color: "var(--red)", fontSize: 13, margin: "8px 0 0" }}>{err}</p>}
      </div>
    );
  }

  return (
    <div className="card" style={{ margin: "10px 0 2px", borderColor: "#D8C89A", background: "#FDFBF5" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
        <span style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: ".6px", color: "#9A6700", flex: 1 }}>🧠 Pre-call brief</span>
        <button className="mini" onClick={copyText}>{copied ? "✓ Copied" : "Copy"}</button>
        <button className="mini" onClick={generate}>↻</button>
        <button onClick={() => { setBrief(null); setState("idle"); }} style={{ background: "none", border: "none", color: "var(--red)", fontWeight: 800, cursor: "pointer", fontSize: 15, lineHeight: 1 }}>×</button>
      </div>
      {brief && (
        <>
          <div style={{ fontSize: 15, fontWeight: 800, lineHeight: 1.4, marginBottom: 12 }}>{brief.headline}</div>
          <Sec t="Situation" items={brief.situation} />
          <Sec t="The money story" items={brief.money} />
          <Sec t="People" items={brief.people} />
          <div style={{ marginBottom: 10 }}>
            <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: ".6px", color: "#9A6700", marginBottom: 3 }}>Opener</div>
            <div style={{ fontSize: 13.5, lineHeight: 1.55, background: "#fff", border: "1px solid #EFE7D6", borderRadius: 8, padding: "9px 11px", fontStyle: "italic" }}>&ldquo;{brief.opener}&rdquo;</div>
          </div>
          <Sec t="Discovery questions" items={brief.questions.map((q, i) => `${i + 1}. ${q}`).map((s) => s)} />
          {brief.proof && (
            <div style={{ marginBottom: 6 }}>
              <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: ".6px", color: "#9A6700", marginBottom: 3 }}>Proof point</div>
              <div style={{ fontSize: 13, lineHeight: 1.5, color: "var(--ink2)" }}>{brief.proof}</div>
            </div>
          )}
          <div style={{ fontSize: 10.5, color: "var(--muted)", marginTop: 8 }}>Built from filings, FERC/EIA data, signals, and your CRM — verify figures before relying on them.</div>
        </>
      )}
    </div>
  );
}
